comment out job that builds images if necessary

diff --git a/.github/workflows/test_on_4_linux.yml b/.github/workflows/test_on_4_linux.yml
--- a/.github/workflows/test_on_4_linux.yml
+++ b/.github/workflows/test_on_4_linux.yml
@@ -15,38 +15,39 @@ env:
 jobs:
 
 #-------------------------------------------------------------------------------
-  build_images:
-    name: Build docker images if necessary
-    runs-on: ubuntu-latest
-
-    strategy:
-      fail-fast: true
-      matrix:
-        os: [ ubuntu, debian, centos, alpine ]
-
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v2
-
-      - name: check modified files
-        id:   check_files
-        run:  |
-          git diff --name-only HEAD^ HEAD | grep Dockerfile
-          echo ::set-output name=check_dockerfiles::$?
-
-      - name: ghcr.io login ... build and publish images if needed
-        uses: docker/login-action@v1
-        if: ${{ steps.check_files.outputs.check_dockerfiles == 0}}
-        with:
-          registry: ghcr.io
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Build and publish new Docker image
-        if: ${{ steps.check_files.outputs.check_dockerfiles == 0 }}
-        run: |
-          docker build -f ${{ env.DOCKERFILE }}_${{ matrix.os }} -t ${{ env.GHRC }}_${{ matrix.os }} .
-          docker push ${{ env.GHRC }}_${{ matrix.os }}
+# TODO: figure out how to build images first if necessary
+#  build_images:
+#    name: Build docker images if necessary
+#    runs-on: ubuntu-latest
+#
+#    strategy:
+#      fail-fast: true
+#      matrix:
+#        os: [ ubuntu, debian, centos, alpine ]
+#
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@v2
+#
+#      - name: check modified files
+#        id:   check_files
+#        run:  |
+#          git diff --name-only HEAD^ HEAD | grep Dockerfile
+#          echo ::set-output name=check_dockerfiles::$?
+#
+#      - name: ghcr.io login ... build and publish images if needed
+#        uses: docker/login-action@v1
+#        if: ${{ steps.check_files.outputs.check_dockerfiles == 0}}
+#        with:
+#          registry: ghcr.io
+#          username: ${{ github.actor }}
+#          password: ${{ secrets.GITHUB_TOKEN }}
+#
+#      - name: Build and publish new Docker image
+#        if: ${{ steps.check_files.outputs.check_dockerfiles == 0 }}
+#        run: |
+#          docker build -f ${{ env.DOCKERFILE }}_${{ matrix.os }} -t ${{ env.GHRC }}_${{ matrix.os }} .
+#          docker push ${{ env.GHRC }}_${{ matrix.os }}
 
 #-------------------------------------------------------------------------------
   all_linux_test:
